import type { KbEntry } from './types';

// ICT / SMC core concepts. Definitions are the precise ones (aligned with the
// coach's precision rules) — each carries the mechanism, when to use / avoid,
// the common mistake, an example, and edges to related concepts.
export const ICT_ENTRIES: KbEntry[] = [
  {
    id: 'liquidity',
    title: 'Liquidity (BSL / SSL)',
    aliases: ['liquidity', 'ליקווידיות', 'נזילות', 'bsl', 'ssl', 'buy-side', 'sell-side', 'draw on liquidity', 'draw on'],
    category: 'ict',
    definition: 'Pools of resting orders — protective stops and pending orders — that sit above old highs (buy-side, BSL) and below old lows (sell-side, SSL). Price is drawn toward them.',
    why: 'Large participants need counterparty orders to fill size. Obvious levels (old highs/lows, equal highs/lows, session highs/lows) pool orders, so price tends to reach for them before the real move.',
    whenUse: 'To identify the "draw on liquidity" — where price is likely headed to fill orders — and to frame targets (the opposing liquidity).',
    whenAvoid: 'Not every high or low is a reversal target. In a strong trend, liquidity gets run and continuation follows rather than a reversal.',
    mistakes: 'Assuming a run of liquidity always reverses — a sweep can equally fuel continuation. Liquidity is a magnet, not a signal on its own.',
    example: 'Equal highs resting above the market act as a magnet; price often runs them (takes BSL) before the genuine move begins.',
    related: ['sweep', 'premium-discount', 'smt', 'fvg', 'dealing-range'],
  },
  {
    id: 'sweep',
    title: 'Liquidity Sweep (the manipulation leg)',
    aliases: ['sweep', 'raid', 'liquidity sweep', 'גירוף', 'לקיחת נזילות', 'stop hunt', 'manipulation leg', 'רגל המניפולציה', 'סוויפ'],
    category: 'ict',
    definition: 'A quick push beyond a liquidity level (old high/low, equal highs/lows) that takes the resting orders and then rejects. This is the manipulation leg.',
    why: 'It is engineered to fill large orders against trapped traders and to create the fuel for the intended move.',
    whenUse: 'As the manipulation that PRECEDES a setup — you wait for what happens AFTER the sweep (displacement + a shift), not the sweep itself.',
    whenAvoid: 'A sweep alone is not an entry or a reversal signal. Without displacement and a structure shift it can simply be continuation.',
    mistakes: 'Entering on the sweep itself and treating the manipulation leg as confirmation. The sweep is bait, not the signal.',
    example: 'Price wicks above PDH, takes buy-side liquidity, then displaces down — the sweep set up the short; it was not the confirmation.',
    related: ['liquidity', 'choch', 'fvg', 'judas-swing', 'displacement'],
  },
  {
    id: 'bos',
    title: 'BOS — Break of Structure',
    aliases: ['bos', 'break of structure', 'שבירת מבנה', 'שבירה בכיוון המגמה'],
    category: 'ict',
    definition: 'A break of a significant swing point IN the direction of the current trend, confirming continuation (a new higher high in an uptrend, a new lower low in a downtrend).',
    why: 'A fresh extreme in the trend direction shows the prevailing order flow is still intact.',
    whenUse: 'To confirm the trend is continuing and to frame with-trend entries.',
    whenAvoid: 'A break on thin or no displacement can be a liquidity run rather than a true BOS — check for intent behind the break.',
    mistakes: 'Confusing a minor swing break with a structural one; not every wick beyond a level is a BOS.',
    example: 'In an uptrend, price closes above the last significant high → BOS, and the trend continues.',
    related: ['choch', 'mss', 'displacement', 'dealing-range'],
  },
  {
    id: 'choch',
    title: 'CHoCH — Change of Character',
    aliases: ['choch', 'change of character', 'שינוי אופי', 'שבירה נגד המבנה', 'צ׳וצ׳'],
    category: 'ict',
    definition: 'The FIRST break AGAINST the existing structure — in an uptrend, breaking a significant prior swing LOW. It can signal a possible shift in control. It is a STRUCTURAL break, not a slowdown.',
    why: 'The first counter-structure break means the side in control failed to extend and the other side took a structural level.',
    whenUse: 'As an early warning of a possible reversal, strongest after a liquidity sweep at a premium/discount extreme.',
    whenAvoid: 'A CHoCH on a low timeframe inside a higher-timeframe trend is often just a pullback — context decides.',
    mistakes: 'Calling any momentum slowdown, change of pace, or volume drop a CHoCH. It is a break of structure, full stop.',
    example: 'An uptrend sweeps buy-side liquidity, then breaks the last higher-low → CHoCH, a possible reversal.',
    related: ['bos', 'mss', 'sweep', 'liquidity'],
  },
  {
    id: 'mss',
    title: 'MSS — Market Structure Shift',
    aliases: ['mss', 'market structure shift', 'שינוי מבנה', 'שינוי מבנה שוק'],
    category: 'ict',
    definition: 'A decisive structure break carried by displacement that marks a genuine change in order flow. Often a strong CHoCH, but MSS emphasizes the momentum/intent behind it.',
    why: 'A shift backed by displacement shows real intent, not just a technical line break.',
    whenUse: 'As confirmation that character has actually changed — the reaction after a sweep.',
    whenAvoid: 'Without displacement it is a weak, possibly false shift.',
    mistakes: 'Treating every CHoCH as an MSS — MSS specifically implies displacement.',
    example: 'After sweeping SSL, price displaces up through the last lower-high with a strong candle → MSS.',
    related: ['choch', 'bos', 'displacement', 'sweep'],
  },
  {
    id: 'fvg',
    title: 'FVG — Fair Value Gap',
    aliases: ['fvg', 'fair value gap', 'פער', 'אי איזון', 'אי-איזון', 'imbalance', 'חוסר איזון', 'gap'],
    category: 'ict',
    definition: 'A 3-candle imbalance where the wicks of candle 1 and 3 do not overlap, leaving an inefficiency price tends to return to and rebalance.',
    why: 'A fast, one-sided move leaves orders unfilled; price often revisits to rebalance before continuing.',
    whenUse: 'As a potential entry/mitigation zone WHEN it aligns with context (bias, structure, premium/discount, a sweep, a clear liquidity target).',
    whenAvoid: 'An FVG on its own is never a sufficient reason to enter; a random gap inside chop means little.',
    mistakes: 'Thinking every FVG is an opportunity, or judging quality by volume. Quality is context — location vs structure, HTF bias, premium/discount, whether it formed from a sweep + displacement, and a clear liquidity target ahead.',
    example: 'A bullish FVG left by a sharp displacement up, sitting in discount, after a sell-side sweep, aligned with an up bias → high quality.',
    related: ['ifvg', 'displacement', 'premium-discount', 'liquidity', 'sweep'],
  },
  {
    id: 'ifvg',
    title: 'IFVG — Inverse Fair Value Gap',
    aliases: ['ifvg', 'inverse fvg', 'inverse fair value gap', 'פער הפוך'],
    category: 'ict',
    definition: 'An FVG that price trades fully through and fails; the failed gap flips polarity and then acts as support/resistance in the opposite direction.',
    why: 'Once an imbalance is violated, the orders that defended it are gone and it becomes a level for the other side.',
    whenUse: 'As confirmation/entry after an FVG fails and flips — often confirming a shift in delivery.',
    whenAvoid: 'It needs a clean break THROUGH the FVG, not a wick; a marginal poke is not an IFVG.',
    mistakes: 'Calling a simple retest an IFVG. It requires the original FVG to actually fail.',
    example: 'A bullish FVG gets fully traded through and closed below → it becomes bearish IFVG resistance.',
    related: ['fvg', 'choch', 'displacement'],
  },
  {
    id: 'smt',
    title: 'SMT Divergence',
    aliases: ['smt', 'smt divergence', 'divergence', 'סמט', 'דיברגנס', 'דיברגנציה'],
    category: 'ict',
    definition: 'Correlated instruments (ES vs NQ, or vs YM) failing to confirm each other\'s high or low — one makes a new extreme, the other does not.',
    why: 'When one index sweeps liquidity but the correlated one does not follow, the move lacks broad participation — a divergence that often precedes a reversal.',
    whenUse: 'As a reversal tell READ against the liquidity being swept on the correlated instrument.',
    whenAvoid: 'SMT without a liquidity context is noise; both legs must sit at meaningful levels.',
    mistakes: 'Using SMT as a standalone signal and ignoring which liquidity was or was not taken.',
    example: 'NQ makes a new high sweeping BSL while ES fails to make a new high → bearish SMT.',
    related: ['liquidity', 'sweep', 'choch'],
  },
  {
    id: 'premium-discount',
    title: 'Premium / Discount (Equilibrium)',
    aliases: ['premium', 'discount', 'פרימיום', 'דיסקאונט', 'equilibrium', 'שיווי משקל', '50%', 'אקוויליבריום'],
    category: 'ict',
    definition: 'A dealing range split at its 50% (equilibrium): above 50% is premium (expensive — favor selling), below 50% is discount (cheap — favor buying).',
    why: 'Institutions want to buy in discount and sell in premium; equilibrium is the fair-value midpoint of the range.',
    whenUse: 'To decide WHERE in the range a setup sits — a long is stronger from discount, a short from premium.',
    whenAvoid: 'Premium/discount is only meaningful relative to a valid, current dealing range; a stale range misleads.',
    mistakes: 'Buying in premium or selling in discount and wondering why the entries are poor.',
    example: 'Price sweeps SSL into deep discount then shifts up → a long from discount aligns with premium/discount logic.',
    related: ['dealing-range', 'liquidity', 'fvg'],
  },
  {
    id: 'judas-swing',
    title: 'Judas Swing',
    aliases: ['judas', 'judas swing', 'יהודה', 'ג׳ודאס', 'false open', 'מהלך כוזב', 'ג׳ודס'],
    category: 'ict',
    definition: 'A false move early in a session (often the London or NY open) that pushes one direction to trap traders and take liquidity, before reversing into the real intraday move.',
    why: 'The open engineers a move against the day\'s true intent to grab stops and fill orders.',
    whenUse: 'Be cautious of the first aggressive push after a session open; wait for the reversal plus a shift.',
    whenAvoid: 'Not every open has a clean Judas swing — don\'t force the label.',
    mistakes: 'Chasing the initial session push and getting trapped by the reversal.',
    example: 'NY opens, spikes up to take buy-side, then reverses down for the day → the up-spike was the Judas swing.',
    related: ['killzones', 'sweep', 'liquidity'],
  },
  {
    id: 'killzones',
    title: 'Killzones / Sessions',
    aliases: ['killzone', 'killzones', 'kill zone', 'קילזון', 'חלונות זמן', 'sessions', 'סשן', 'סשנים', 'ny am', 'london killzone'],
    category: 'ict',
    definition: 'The specific high-probability time windows ICT traders focus on — London, NY AM, NY PM, and the London close — when institutional activity and volatility concentrate.',
    why: 'Liquidity and participation cluster around session opens; the day\'s manipulation and distribution often happen in these windows.',
    whenUse: 'To time setups — take entries during the relevant killzone, not in dead hours.',
    whenAvoid: 'Outside the killzones, or on low-liquidity holidays, setups are lower quality.',
    mistakes: 'Trading all day the same way, ignoring that most of the edge sits in specific windows.',
    example: 'The NY AM killzone sweeps overnight liquidity then delivers the primary move of the session.',
    related: ['judas-swing', 'liquidity'],
  },
  {
    id: 'dealing-range',
    title: 'Dealing Range',
    aliases: ['dealing range', 'דילינג ריינג', 'range', 'טווח מסחר', 'טווח'],
    category: 'ict',
    definition: 'The current swing high to swing low the market is trading between — the reference range whose 50% defines premium/discount and whose extremes hold the liquidity.',
    why: 'It frames where price is expensive vs cheap and where the draws on liquidity sit.',
    whenUse: 'To anchor premium/discount and to know which liquidity is in play.',
    whenAvoid: 'An outdated range (after a strong break) must be redrawn; a stale range gives wrong premium/discount reads.',
    mistakes: 'Not updating the range after a structure break, so premium/discount is measured against the wrong swing.',
    example: 'From the last significant low to the last significant high is the dealing range; its midpoint is equilibrium.',
    related: ['premium-discount', 'liquidity', 'bos'],
  },
  {
    id: 'displacement',
    title: 'Displacement',
    aliases: ['displacement', 'דיספלייסמנט', 'תנועה חדה', 'impulse', 'אימפולס', 'תנועה אימפולסיבית'],
    category: 'ict',
    definition: 'A strong, one-sided move (a large-bodied candle or sequence) that shows real intent and typically leaves an FVG — the signature of a genuine shift versus a weak drift.',
    why: 'Institutions moving size leave displacement and imbalance behind; it is the intent behind a break.',
    whenUse: 'To validate that a structure break (BOS/CHoCH/MSS) is real, and to locate the FVG it left.',
    whenAvoid: 'A break WITHOUT displacement is suspect — likely a liquidity run, not a true shift.',
    mistakes: 'Treating a slow, overlapping break as a valid shift when there was no displacement.',
    example: 'After sweeping SSL, a large bullish candle blasts through the last lower-high, leaving an FVG → displacement confirms the shift.',
    related: ['fvg', 'mss', 'choch', 'bos'],
  },
];
